# Umgebungen umgibt unglaubliches

Lesen Sie das ["Environments"](https://adv-r.hadley.nz/environments.html)-Kapitel aus *Advanced R Programming* aufmerksam durch. 

Bearbeiten Sie die folgenden, teilweise von dort übernommenen Aufgaben:

a) Inwiefern unterscheiden sich in R Listen (`list`) von `environment`s?

Listen sind geordnet, sodass per numerischer Indizierung auf Elemente zugegriffen werden kann; das trifft auf Environments nicht zu.
Bei Modifikationen eines Environments werden Elemente direkt in-place geändert (ohne Erstellung von Kopien).
Bindings in Environments müssen explizit gelöst werden - ein Element auf `NULL`zu setzen, entfernt nicht das Binding, sondern bindet das Element an den Wert `NULL`.

b) Wo suchen `ls()` und `rm()` wenn nicht explizit ein `environment` angegeben wird?

Im aktuell aktiven environment (für `inherits = TRUE` werden die Elternumgebungen so lange durchsucht, bis ein Element des angegebenen Namens gefunden wird).

c) Wo legt `<-` eine (neue) `binding` an? Wo `<<-`?

`<-` führt die Zuweisung immer im aktuell aktiven Environment durch. `<<-` geht immer mindestens eine Ebene höher und sucht so lange in Elternumgebungen, bis es die Variable dort findet und setzt dann das binding. Existiert die Variable in keiner Elternumgebung, wird sie im globalen Environment angelegt.

d) Schreiben sie eine modifizierte Version `anywhere()` der Funktion `where()` aus dem `pryr`-Paket (**nicht** der im Buch definierten Funktion `where`), die *alle* Umgebungen im Suchpfad, die eine Variable des gegebenen Namens enthalten, in Form einer Liste zurückgibt. Überprüfen Sie ihre Implementation mit `test-env-anywhere.R`.

```{r, where}

anywhere <- function(name, env = parent.frame()) {
  
  checkmate::assert_string(name)
  checkmate::assert_environment(env)
  
  env <- pryr:::to_env(env)

  list_environments <- list()
  
  while (!identical(env, emptyenv())) {
    
    if (exists(name, env, inherits = FALSE)) {
      list_environments <- append(list_environments, env)
    }
    env <- parent.env(env)
    
  }
  
  list_environments
  
}

anywhere("t", env = e0)

```

*Hinweis:* Die Funktion `to_env()`, die in `pryr::where()` benutzt wird wird nicht von `pryr` exportiert. Sie können die Funktion trotzdem mittels `pryr:::to_env()` aufrufen.


